name: publish

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install cargo components
        run: rustup component add clippy
      - name: run tests
        run: .github/scripts/test.sh
      - name: login to crates.io
        run: cargo login ${{ secrets.CRATESIO }}
      - name: publish CRATE
        run: .github/scripts/publish.sh CRATE
